### PR TITLE
Adding compliance tests

### PR DESCRIPTION
**Pull request by johanfylling**
Lots, and lots of test cases extracted from OPA (https://github.com/open-policy-agent/opa/tree/main/test/cases/testdata) serialized as json.

Many of them failing for a plethora of reasons.

Signed-off-by: Johan Fylling <johan.dev@fylling.se>

### CODE REVIEW

**Comment by anderseknert** [comment]
Very interesting, awesome work! 👏 

Seems like we have some work ahead of us 😆

It's a bit too much to digest currently — we should probably disable the tests initially and then have them enabled per topic / built-in gradually, or what do you think?

One thing I noticed is that many tests actually seem to produce the expected outcome, but the result from running OPA is JSON serialized, and ours don't seem to be, so we're failing whenever we return e.g. a set rather than an array. This should be a low-hanging fruit:

```
 FAIL in (aggregates_min_out-of-order) (compliance_test.clj:46)
expected: (= result want-result)
  actual: (not (= {"p" #{-7}} {"p" [-7]}))
Expected: {p 1}

Got: {p 1}
```

Not sure about what that last:

```
Expected: {p 1}

Got: {p 1}
```

is about though.

**Comment by johanfylling** [comment]
Lots of work ahead, indeed 😄 .

Yes, there's plenty of low hanging fruit here. Many of them because the test suite isn't entirely complete yet, even. E.g. expected errors aren't handled; and `data` can't be fed to the evaluator the same way `input` can. My plan is to take care of some of these fruits before making this PR non-draft.

We should definitely be selective about what tests we run automatically; disabling those we know shouldn't work yet because of missing implementations (not bugs). Haven't looked into how to best achieve that yet, though.

**Comment by anderseknert** [comment]
Sounds good! I suppose one place to start could be to only include the builtins listed in the registry.clj file.

**Comment by johanfylling** [comment]
Yea. Probably good to automate (though this already has a heavy ad-hoc smell 😅 ). Naïvely string matching the policies (we hava access to the AST in the test generator, so we can go more advanced, if need be), we could perhaps include a list of each built-in used for every test-case, and filter by that on the consumer-side 🤔 .

**Comment by anderseknert** [comment]
Yeah, as far as I could see, the plan already provides a map of all the built-ins being used for evaluation, so that should be "easy" to use as a filter.

**Comment by johanfylling** [comment]
Yes, you're correct. Forgot about that. That makes things much easier. Will add an automated filter based on the listing in `registry.clj` 👍 .

**Pull request merged**
