### PR TITLE
Include location in builtin exceptions

### LINKED ISSUE #9: Include location in built-in function call invocation
In order to mimic the OPA error messages, we should include the original location when built-in functions are called.

### PR DESCRIPTION
**Pull request by anderseknert**
Fixes #9

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Review by johanfylling — COMMENTED** [review]
There are places in the evaluator that also throws errors that, for completeness, should probably also be updated.

A couple of tests would be nice.

**Comment by anderseknert** [comment]
Thanks, will take a look at those tonight!

**Comment by anderseknert** [comment]
> There are places in the evaluator that also throws errors that, for completeness, should probably also be updated.

What location would they include though? Or do you have an example I can work with?

**Comment by johanfylling** [comment]
> What location would they include though?

Each statement declaration in the IR should come with it's own location info, I think.

> Or do you have an example I can work with?

* `eval-AssignVarOnceStmt`, e.g.: https://play.openpolicyagent.org/p/v4ltBQ63hG, and https://play.openpolicyagent.org/p/1884AjyN6O
* `eval-ObjectInsertOnceStmt`, e.g.: https://play.openpolicyagent.org/p/FeglE7fG4f

**Comment by anderseknert** [comment]
I started looking into this, and doing this in a clean way would require refactoring of our exception handling entirely, to not just throw with a message, but rather with a map of arbitrary data including things like location... ironically, this is how logging is intended to work in Clojure.. we just kinda Javafied it out of habit I suppose. I suggest we merge this, and then I'll create a new issue for refactoring our exception handling.

**Review by johanfylling — APPROVED** [review]
👍

**Pull request merged**
